/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.architectury.loom").version("1.10.433")
}

group = "li.sailor.petilil"
version = "25.0.0"

repositories {
    maven(url = "https://maven.gtceu.com") {
        content { includeGroupAndSubgroups("com.gregtechceu.gtceu") }
    }
    maven(url = "https://maven.tterrag.com/") {
        content {
            includeGroupAndSubgroups("com.tterrag.registrate")
        }
    }
    maven(url = "https://maven.firstdarkdev.xyz/snapshots")
    maven(url = "https://maven.terraformersmc.com/") {
        content {
            includeGroupAndSubgroups("dev.emi")
        }
    }
}

loom.forge {
    mixinConfig("petilil.mixins.json")
}

dependencies {
    minecraft("net.minecraft:minecraft:1.20.1")
    mappings(loom.officialMojangMappings())
    forge("net.minecraftforge:forge:1.20.1-47.4.4")

    // ?
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")!!)
    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1")!!)

    // the gtceu pom doesn't have deps? why?
    modImplementation("com.lowdragmc.ldlib:ldlib-forge-1.20.1:1.0.41.b") {
        // this one does have transient deps but they're all eexported??!?!
        exclude(group = "appeng")
        exclude(group = "dev.latvian.mods")
        exclude(group = "mezz.jei")
    }
    // why.
    modImplementation("com.tterrag.registrate:Registrate:MC1.20-1.3.11")
    modImplementation("dev.toma.configuration:configuration-forge-1.20.1:2.2.0")
    modApi("com.gregtechceu.gtceu:gtceu-1.20.1:7.0.2")

    modRuntimeOnly("dev.emi:emi-forge:1.1.22+1.20.1")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }

    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

